In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
credit = pd.read_csv('../data/creditcard.csv')
fraud = pd.read_csv('../data/processed/X_resampled.csv')

In [3]:
credit.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [4]:
fraud.head()

,purchase_value,age,ip_address,ip_address_int,lower_bound_ip_address,upper_bound_ip_address,transaction_count,total_amount,avg_amount,velocity,...,country_Uruguay,country_Uzbekistan,country_Vanuatu,country_Venezuela,country_Viet Nam,country_Virgin Islands (U.S.),country_Yemen,country_Zambia,country_Zimbabwe,class
0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,...,0.0,0.549607,0.549607,0.0,-1.231124,1.487911,-0.413800,1.008263,0.664645,0
1,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,-1.197335,-1.197335,0.0,1.229002,-0.505034,-1.180852,-1.182488,-1.518365,0
2,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.385831,0.385831,0.0,1.663142,0.989675,-0.936126,-0.450875,-0.794408,0
3,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.986342,0.986342,0.0,0.650149,0.989675,0.867086,-0.794479,-0.283797,0
4,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.767974,0.767974,0.0,-1.086411,-1.003270,1.700633,1.145288,1.717574,0

In [5]:
import sys
sys.path.append("../src")  # so you can import your src files

from model_training import train_and_evaluate

In [6]:
# Train on creditcard dataset
train_and_evaluate("../Data/creditcard.csv", target_col="Class", model_name_prefix="creditcard")

# Train on fraud data dataset
train_and_evaluate("../Data/processed/X_resampled.csv", target_col="class", model_name_prefix="frauddata")

[INFO] Data loaded from: ../Data/creditcard.csv
[INFO] Shape: (284807, 30), Target distribution: {0: 284315, 1: 492}

d:\Project\10 Academy Resourse\Week 8_9\Fraud-Detection-Model\fraud-venv\Lib\site-packages\sklearn\linear_model\_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

[INFO] F1 Score: 0.0900, AUC-PR: 0.7364
[INFO] F1 Score: 0.8457, AUC-PR: 0.8589
[INFO] Logistic Regression metrics: {'f1_score': 0.08995502248875563, 'auc_pr': np.float64(0.7363566045812515), 'confusion_matrix': [[55051, 1813], [8, 90]]}
[INFO] Random Forest metrics: {'f1_score': 0.8457142857142858, 'auc_pr': np.float64(0.8589278575500874), 'confusion_matrix': [[56861, 3], [24, 74]]}
[INFO] Models saved to: D:\Project\10 Academy Resourse\Week 8_9\Fraud-Detection-Model\models
[INFO] Metrics saved to: D:\Project\10 Academy Resourse\Week 8_9\Fraud-Detection-Model\results\metrics_creditcard.json
[INFO] Data loaded from: ../Data/processed/X_resampled.csv
[INFO] Shape: (233756, 206), Target distribution: {0: 116878, 1: 116878}
[INFO] F1 Score: 0.6863, AUC-PR: 0.8330
[INFO] F1 Score: 0.9708, AUC-PR: 0.9961
[INFO] Logistic Regression metrics: {'f1_score': 0.6862914862914863, 'auc_pr': np.float64(0.8329716527199016), 'confusion_matrix': [[17164, 6212], [7919, 15457]]}
[INFO] Random Forest metrics: {'f1_score': 0.9708131868131868, 'auc_pr': np.float64(0.9960660508684512), 'confusion_matrix': [[23338, 38], [1290, 22086]]}
[INFO] Models saved to: D:\Project\10 Academy Resourse\Week 8_9\Fraud-Detection-Model\models
[INFO] Metrics saved to: D:\Project\10 Academy Resourse\Week 8_9\Fraud-Detection-Model\results\metrics_frauddata.json